// main.cpp -- test harness for Practical 1: The Study Squad Tracker
//
// DO NOT EDIT THIS FILE.
// The grader uses this exact main.cpp. Any changes you make here will be
// overwritten before grading.
//
// This program reads a test ID from stdin, then reads the test-specific
// inputs, calls the appropriate function in your Squad namespace, and
// prints the result. Each test corresponds to one input file in
// tests/inputs/ and one expected output file in tests/expected/.

#include <iostream>
#include <string>
#include "Squad.h"

int main() {
    int test_id;
    std::cin >> test_id;

    if (test_id == 1) {
        // addHours: basic
        int current, hours;
        std::cin >> current >> hours;
        std::cout << SQUAD::addHours(current, hours) << std::endl;
    }
    else if (test_id == 2) {
        // incrementSessions: basic
        int count;
        std::cin >> count;
        std::cout << SQUAD::incrementSessions(count) << std::endl;
    }
    else if (test_id == 3) {
        // calculateAverage: normal
        double total;
        int count;
        std::cin >> total >> count;
        std::cout << SQUAD::calculateAverage(total, count) << std::endl;
    }
    else if (test_id == 4) {
        // calculateAverage: divide-by-zero
        double total;
        int count;
        std::cin >> total >> count;
        std::cout << SQUAD::calculateAverage(total, count) << std::endl;
    }
    else if (test_id == 5) {
        // scaleHours: basic
        int hours;
        double factor;
        std::cin >> hours >> factor;
        std::cout << SQUAD::scaleHours(hours, factor) << std::endl;
    }
    else if (test_id == 6) {
        // isOnFire: at threshold
        int sessions;
        std::cin >> sessions;
        std::cout << SQUAD::isOnFire(sessions) << std::endl;
    }
    else if (test_id == 7) {
        // isPassing: at threshold
        double avg;
        std::cin >> avg;
        std::cout << SQUAD::isPassing(avg) << std::endl;
    }
    else if (test_id == 8) {
        // canTutor: both pass
        double avg;
        int sessions;
        std::cin >> avg >> sessions;
        std::cout << SQUAD::canTutor(avg, sessions) << std::endl;
    }
    else if (test_id == 9) {
        // canTutor: average fails
        double avg;
        int sessions;
        std::cin >> avg >> sessions;
        std::cout << SQUAD::canTutor(avg, sessions) << std::endl;
    }
    else if (test_id == 10) {
        // setReminder: single param
        int hours;
        std::cin >> hours;
        SQUAD::setReminder(hours);
    }
    else if (test_id == 11) {
        // setReminder: minutes unit
        int value;
        std::string unit;
        std::cin >> value >> unit;
        SQUAD::setReminder(value, unit);
    }
    else if (test_id == 12) {
        // printSessionLog: exact format
        // name uses getline because it may contain spaces
        std::string name;
        int sessions, hours;
        double average;
        std::cin.ignore();
        std::getline(std::cin, name);
        std::cin >> sessions >> hours >> average;
        SQUAD::printSessionLog(name, sessions, hours, average);
    }
    else if (test_id == 13) {
        // processMember: full orchestrator (Squad Star case)
        std::string name;
        int sessions, hours;
        double average;
        std::cin.ignore();
        std::getline(std::cin, name);
        std::cin >> sessions >> hours >> average;
        bool result = SQUAD::processMember(name, sessions, hours, average);
        std::cout << "Squad Star: " << result << std::endl;
    }
    else if (test_id == 14) {
        // isOnFire: below threshold
        int sessions;
        std::cin >> sessions;
        std::cout << SQUAD::isOnFire(sessions) << std::endl;
    }
    else if (test_id == 15) {
        // isPassing: below threshold
        double avg;
        std::cin >> avg;
        std::cout << SQUAD::isPassing(avg) << std::endl;
    }
    else if (test_id == 16) {
        // canTutor: sessions short
        double avg;
        int sessions;
        std::cin >> avg >> sessions;
        std::cout << SQUAD::canTutor(avg, sessions) << std::endl;
    }
    else if (test_id == 17) {
        // setReminder: hours unit (no conversion)
        int value;
        std::string unit;
        std::cin >> value >> unit;
        SQUAD::setReminder(value, unit);
    }
    else if (test_id == 18) {
        // setReminder: 90 minutes (integer division truncation)
        int value;
        std::string unit;
        std::cin >> value >> unit;
        SQUAD::setReminder(value, unit);
    }
    else if (test_id == 19) {
        // scaleHours: fractional result
        int hours;
        double factor;
        std::cin >> hours >> factor;
        std::cout << SQUAD::scaleHours(hours, factor) << std::endl;
    }
    else if (test_id == 20) {
        // processMember: not a Squad Star
        std::string name;
        int sessions, hours;
        double average;
        std::cin.ignore();
        std::getline(std::cin, name);
        std::cin >> sessions >> hours >> average;
        bool result = SQUAD::processMember(name, sessions, hours, average);
        std::cout << "Squad Star: " << result << std::endl;
    }

    return 0;
}
